const data = {
  products: [
    {
      name: 'Blanqueador',
      slug: 'Blanqueador',
      category: 'General',
      image: '/images/blanqueador.png',
      price: 6500,
      marca: 'Suramar',
      rating: 4.5,
      numReviews: 8,
      CountinStock: 20,
      description: 'Limpiador y desifectante de uso general',
    },
    {
      name: 'Blanqueador Ropa Color',
      slug: 'Blanqueador Ropa Color',
      category: 'Ropa',
      image: '/images/blanqueadorcolor.png',
      price: 8500,
      marca: 'Suramar',
      rating: 4.5,
      numReviews: 8,
      CountinStock: 20,
      description: 'Limpiador y desifectante para ropa color',
    },
    {
      name: 'Limpiavidrios',
      slug: 'Limpiavidrios',
      category: 'General',
      image: '/images/limpiavidrio.png',
      price: 9500,
      marca: 'Suramar',
      rating: 4.5,
      numReviews: 8,
      CountinStock: 20,
      description: 'Limpiador de vidrios',
    },
    {
      name: 'Eliminador de Olores',
      slug: 'Eliminador de Olores',
      category: 'General',
      image: '/images/eliminadorOlores.png',
      price: 19500,
      marca: 'Primal',
      rating: 4.5,
      numReviews: 8,
      CountinStock: 20,
      description: 'Eliminador de olores',
    },
    {
      name: 'Desengrasante',
      slug: 'Desengrasante',
      category: 'General',
      image: '/images/desengrasante.png',
      price: 12500,
      marca: 'Primal',
      rating: 4.5,
      numReviews: 8,
      CountinStock: 20,
      description: 'Desengrasante limpiador',
    },
    {
      name: 'Desengrasante Industrial',
      slug: 'Desengrasante Insdusterial',
      category: 'Industria',
      image: '/images/desenind.png',
      price: 14500,
      marca: 'Primal',
      rating: 4.5,
      numReviews: 8,
      CountinStock: 20,
      description: 'Desengrasante limpiador',
    },
  ],
};

export default data;
